spring.application.name=Monitoring System

# 1. Expose endpoints
management.endpoints.web.exposure.include=*
management.endpoint.prometheus.enabled=true

# 2. Enable Histogram Buckets (The "Gold Standard" for Prometheus)
# This creates the 'le' (less than or equal to) buckets needed for histogram_quantile queries
management.metrics.distribution.percentiles-histogram.http.server.requests=true

# 3. (Optional) Client-side Percentiles
# Only add this if you want the app to calculate P95/P99 itself (less flexible than histograms)
# management.metrics.distribution.percentiles.http.server.requests=0.95, 0.99

server.port=8080
